# fly.toml app configuration file generated for slack-fly on 2025-06-09T20:37:41+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slack-fly'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
